services:
  postgres-db:
    image: postgres:16-alpine
    container_name: music_streaming_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=musicuser
      - POSTGRES_PASSWORD=musicpass
      - POSTGRES_DB=music_streaming
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - music-network

  music-app:
    build: .
    container_name: music_streaming_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/music_streaming
      - SPRING_DATASOURCE_USERNAME=musicuser
      - SPRING_DATASOURCE_PASSWORD=musicpass
    depends_on:
      - postgres-db
    networks:
      - music-network



volumes:
  postgres-data:

networks:
  music-network:
    driver: bridge